CREATE TABLE IF NOT EXISTS task_comments (
  id SERIAL PRIMARY KEY,
  task_id INTEGER NOT NULL REFERENCES tasks(id),
  assignee_id INTEGER NOT NULL REFERENCES assignees(id),
  text VARCHAR(100) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);